apiVersion: v2
name: openshift-logforwarding-splunk
description: Log Forwarding from OpenShift to Splunk
version: 0.0.1
appVersion: 0.0.1
sources:
  - https://github.com/elastic/kibana
maintainers:
- email: andy.block@gmail.com
  name: Andrew Block
home: https://github.com/sabre1041/openshift-logforwarding-splunk
